apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress-dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gebeya-mood-api-dev
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: "dev.gebeya-mood.et5el.gebeya.co"
      http:
        paths:
          - path: /*
            backend:
              serviceName: sample-service
              servicePort: 3000
