apiVersion: v1
kind: Service
metadata:
  name: api-service-dev
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: api-service-dev
    role: sample
